plugins {
	id 'net.fabricmc.fabric-loom'
	id 'com.modrinth.minotaur'
}

base {
	archivesName = 'custom-blocks'
}

ext.modrinthProjectId = 'custom-blocks-pilniczek'
ext.modrinthTitle = 'Custom Blocks'

apply from: rootProject.file('gradle/mod-conventions.gradle')

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}
